---
# tasks file for apache
- name: Instalacion Apache 2.4
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes

- name: Instalaci贸n de php para Apache 2.4
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
  - libapache2-mod-php
  - php-mysqli
  - php
  notify: reinicio_apache2
  
#- name: Configurar tmpPrivateapache
#  command: sed -i -e 's,PrivateTmp=true,PrivateTmp=false\nNoNewPrivileges=yes,g' /lib/systemd/system/apache2.service

#- name: Refresacamos demonio
#  command: systemctl daemon-reload

- name: Copiar php.ini
  ansible.builtin.copy:
    src: php.ini
    dest: /etc/php/8.1/apache2/php.ini
  notify: reinicio_apache2

- name: Copiar virtualhost
  ansible.builtin.copy:
    src: sitio.conf
    dest: /etc/apache2/sites-available/sitio.conf
  notify: reinicio_apache2

- name: Copiar contenido web
  ansible.builtin.copy:
    src: index.php
    dest: /var/www/html/index.php
    
- name: Comprobaci贸n de habilitaci贸n del sitio
  stat:
    path: /etc/apache2/sites-enabled/sitio.conf
  register: sitio_habilitado

- name: Habilitaci贸n de sitio en Apache 2.4
  command: a2ensite sitio.conf
  notify: reinicio_apache2
  when: not sitio_habilitado.stat.exists
