---
- name: Sincronizar la hora
  hosts: all
  remote_user: root
  tasks:
  - name: Instalar ntp
    ansible.builtin.apt:
      name: ntp
      state: present
    update_cache: yes
      
  - name: Configurar ntp
    ansible.builtin.copy:
      src: ntp.conf
      dest: /etc/ntp.conf
    notify: reinicio_ntp

  handlers:
    - name: reinicio_ntp
      ansible.builtin.service:
        name: ntp
        state: restarted

- name: Configurar servidores web
  hosts: ipsWEB
  remote_user: root
  roles:
    - apache

- name: Configurar balanceador web
  hosts: ipsbcw
  remote_user: root
  roles:
    - haproxy

- name: Configurar bases de datos
  hosts: ipsBD
  remote_user: root
  roles:
    - mariadb

- name: Configurar balanceador de bases de datos
  remote_user: root
  hosts: ipsbcbd
  vars:
    puerto1: 3306
    grupo1: ipsBD
    puerto2: 24007
    grupo2: ipsGFS
    modo: tcp
    opcion: tcplog
  roles:
    - haproxy

- name: Configurar GlusterFS
  hosts: ipsGFS
  remote_user: root
  roles:
    - glusterfs


