---
- name: Sincronización de la hora
  hosts: all
  remote_user: root
  roles:
    - ntp

- name: Configuracion de servidores web (apache 2.4)
  hosts: ipsWEB
  remote_user: root
  roles:
    - apache

- name: Configuración de servidor de balanceo de carga para los servidores web (apache 2.4)
  hosts: ipsbcw
  remote_user: root
  roles:
    - haproxy

- name: Configuración de las bases de datos (maridb) - Sin galera cluster
  hosts: ipsBD
  remote_user: root
  roles:
    - mariadb

- name: Configuración del balanceador de base de datos (mariadb) y de sistema de archivos compartido (glusterfs)
  remote_user: root
  hosts: ipsbcbd
  vars:
    puerto1: 3306
    grupo1: ipsBD
    puerto2: 24007
    grupo2: ipsGFS
    modo: tcp
    opcion: tcplog
  roles:
    - haproxy

- name: Configuración de sistema de archivos compartido (glusterfs)
  hosts: ipsGFS
  remote_user: root
  roles:
    - glusterfs


