- name: Cliente Gluster
  hosts: ipsWEB
  tasks:
    - name: Instalación fuse 
      apt:
        name: fuse
        state: present

    - name: Instalación cliente gluster
      apt:
        name: glusterfs-client
        state: present
    - name: Hacer algo para fuse funcione
      command: mknod -m 666 /dev/fuse c 10 229
      ignore_errors: yes
      
    # - name: Habiliar fuse
    #   modprobe:
    #     name: fuse
    #     state: present
    #   ignore_errors: yes

    - name: Creación de carpeta de montaje
      file:
        path: /mnt/web
        state: directory

    - name: Montaje el FS
      mount:
        path: /mnt/web
        src: 10.0.1.200:/vol_web
        fstype: glusterfs
        state: mounted
