- name: Configurar Proxmox
  hosts: proxmox
  remote_user: root
  vars:
    contra_terraform: abc123.
    usuario_terraform: terraform_user@pve
    plantillaLXC_22: "ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
    ubuntu: "local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
    nodo01: "pve"
    ruta: "~/proyectoAnsible/"

  tasks:
    - name: Copiamos los archivos de ansible al servidor Proxmox
      ansible.builtin.copy:
        src: ansible_proxmox/
        dest: /etc/ansible

    - name: Copiamos los archivos de configuracion de iptables
      ansible.builtin.copy:
        src: iptables.sh
        dest: /root/iptables.sh
        mode: 700

    - name: Copiamos el archivo de redes de Proxmox
      ansible.builtin.copy:
        src: redes-proxmox
        dest: /etc/network/interfaces.d/redes-proxmox
      notify: reinicio_networking

    - name: Activamos el enrutamiento
      ansible.builtin.copy:
        src: sysctl.conf
        dest: /etc/sysctl.conf
      notify: reinicio_networking

    - name: Eliminamos los repositorios de pve-enterprise y ceph
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/pve-enterprise.list
        - /etc/apt/sources.list.d/ceph.list

    - name: Instalamos iptables-persistent, python3, python3-jinja2, ansible y software-properties-common
      ansible.builtin.apt:
        name:
          - iptables-persistent
          - python3
          - ansible
          - python3-jinja2
          - software-properties-common
        state: present
        update_cache: yes
        
    - name: Ejecutamos el script de iptables
      ansible.builtin.command: /root/iptables.sh

    - name: Descargamos plantilla para los contenedores LXC
      ansible.builtin.command: pveam download local "{{ plantillaLXC_22 }}"
      ignore_errors: yes

    - name: Creación del usuario para Terrafor
      ansible.builtin.command: "{{ item }}" 
      loop:
       - /sbin/pveum role add TerraformProv -privs "Datastore.AllocateSpace Datastore.Audit Pool.Allocate Sys.Audit Sys.Console Sys.Modify VM.Allocate VM.Audit VM.Clone VM.Config.CDROM VM.Config.Cloudinit VM.Config.CPU VM.Config.Disk VM.Config.HWType VM.Config.Memory VM.Config.Network VM.Config.Options VM.Migrate VM.Monitor VM.PowerMgmt SDN.Use"
       - /sbin/pveum user add {{ usuario_terraform }} --password {{ contra_terraform }}
       - /sbin/pveum aclmod / -user {{ usuario_terraform }} -role TerraformProv
      ignore_errors: yes

    - name: Generamos claves SSH para usar en los contenedores LXC
      community.crypto.openssh_keypair:
        path: /root/.ssh/ansible_key
        comment: Clave Ansible
      register: ssh_key

    - name: Creamos el archivo de variables para Terraform
      ansible.builtin.template:
        src: plantillas/plantilla.var.terraform.j2
        dest: vars_terraform.tf
        
    - name: Recuperamos el archivo de variables de Terraform
      ansible.builtin.fetch:
        src: /root/vars_terraform.tf
        dest: "{{ruta}}terraform/vars_terraform.tf"  
        flat: yes

    - name: Eliminamos el archivo de variables de Terraform del servidor Proxmox
      ansible.builtin.file:
        path: "/root/vars_terraform.tf"
        state: absent
        
  handlers:
    - name: reinicio_networking
      ansible.builtin.service:
        name: networking.service
        state: restarted
        
